import type { DashboardService, DashboardSnapshot } from "@/lib/types";

function now() {
  return new Date().toISOString();
}

export function getDemoSnapshot(extraIssues: string[] = []): DashboardSnapshot {
  const checkedAt = now();

  const services: DashboardService[] = [
    {
      id: "inventree.caddy.lan",
      displayName: "Inventree",
      record: "inventree.caddy.lan",
      url: "https://inventree.caddy.lan",
      hostnames: ["inventree.caddy.lan"],
      listeners: ["192.168.233.176:443"],
      routeType: "reverse_proxy" as const,
      mappedTo: ["inventree.lan:80"],
      upstreams: ["inventree.lan:80"],
      notes: ["Simple reverse proxy"],
      sourcePaths: ["apps.http.servers.edge.routes[0]"],
      transportHint: "http" as const,
      lastUpdated: checkedAt,
      overallStatus: "up" as const,
      backend: {
        state: "up" as const,
        label: "TCP open",
        latencyMs: 12,
        checkedAt,
      },
    },
    {
      id: "silverbullet.caddy.lan",
      displayName: "Silverbullet",
      record: "silverbullet.caddy.lan",
      url: "https://silverbullet.caddy.lan",
      hostnames: ["silverbullet.caddy.lan"],
      listeners: ["192.168.233.176:443"],
      routeType: "reverse_proxy" as const,
      mappedTo: ["127.0.0.1:3000"],
      upstreams: ["127.0.0.1:3000"],
      notes: ["Frontend healthy, backend flapping"],
      sourcePaths: ["apps.http.servers.edge.routes[1]"],
      transportHint: "http" as const,
      lastUpdated: checkedAt,
      overallStatus: "down" as const,
      backend: {
        state: "down" as const,
        label: "Connection refused",
        checkedAt,
        detail: "Upstream responded and then stopped accepting connections.",
      },
    },
    {
      id: "cloudcli.caddy.lan",
      displayName: "Cloudcli",
      record: "cloudcli.caddy.lan",
      url: "https://cloudcli.caddy.lan",
      hostnames: ["cloudcli.caddy.lan"],
      listeners: ["192.168.233.176:443"],
      routeType: "reverse_proxy" as const,
      mappedTo: ["127.0.0.1:3001"],
      upstreams: ["127.0.0.1:3001"],
      notes: ["Operator UI"],
      sourcePaths: ["apps.http.servers.edge.routes[2]"],
      transportHint: "http" as const,
      lastUpdated: checkedAt,
      overallStatus: "up" as const,
      backend: {
        state: "up" as const,
        label: "TCP open",
        latencyMs: 9,
        checkedAt,
      },
    },
    {
      id: "farfield.caddy.lan",
      displayName: "Farfield",
      record: "farfield.caddy.lan",
      url: "https://farfield.caddy.lan",
      hostnames: ["farfield.caddy.lan"],
      listeners: ["192.168.233.176:443"],
      routeType: "reverse_proxy" as const,
      mappedTo: ["127.0.0.1:4312"],
      upstreams: ["127.0.0.1:4312"],
      notes: ["Self-hosted Farfield UI"],
      sourcePaths: ["apps.http.servers.edge.routes[3]"],
      transportHint: "http" as const,
      lastUpdated: checkedAt,
      overallStatus: "up" as const,
      backend: {
        state: "up" as const,
        label: "TCP open",
        latencyMs: 11,
        checkedAt,
      },
    },
    {
      id: "notes.caddy.lan",
      displayName: "Notes",
      record: "notes.caddy.lan",
      url: "https://notes.caddy.lan",
      hostnames: ["notes.caddy.lan"],
      listeners: ["192.168.233.176:443"],
      routeType: "file_server" as const,
      mappedTo: ["/srv/notes"],
      upstreams: [],
      notes: ["Static file server"],
      sourcePaths: ["apps.http.servers.edge.routes[4]"],
      transportHint: "unknown" as const,
      lastUpdated: checkedAt,
      overallStatus: "unknown" as const,
      backend: {
        state: "na" as const,
        label: "n/a",
        checkedAt,
      },
    },
    {
      id: "old.caddy.lan",
      displayName: "Old Redirect",
      record: "old.caddy.lan",
      url: "http://old.caddy.lan",
      hostnames: ["old.caddy.lan"],
      listeners: ["192.168.233.176:80"],
      routeType: "redirect" as const,
      mappedTo: ["https://new.caddy.lan"],
      upstreams: [],
      notes: ["Explicit redirect"],
      sourcePaths: ["apps.http.servers.edge.routes[5]"],
      transportHint: "unknown" as const,
      lastUpdated: checkedAt,
      overallStatus: "unknown" as const,
      backend: {
        state: "na" as const,
        label: "n/a",
        checkedAt,
      },
    },
  ];

  return {
    summary: {
      total: services.length,
      up: services.filter((service) => service.overallStatus === "up").length,
      warn: services.filter((service) => service.overallStatus === "warn").length,
      down: services.filter((service) => service.overallStatus === "down").length,
      unknown: services.filter((service) => service.overallStatus === "unknown")
        .length,
      unhealthy: services.filter((service) =>
        ["warn", "down", "unknown"].includes(service.overallStatus),
      ).length,
      generatedAt: checkedAt,
    },
    source: {
      kind: "demo",
      label: "Bundled demo data",
      checkedAt,
      issues: extraIssues,
    },
    services,
  };
}
